/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle */

#ifndef _Included_org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle
#define _Included_org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle
 * Method:    generateRandomState
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle_generateRandomState
        (JNIEnv *, jobject, jstring);

/*
 * Class:     org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle
 * Method:    solveState
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle_solveState
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle
 * Method:    invertAlgorithm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_worldcubeassociation_tnoodle_binding_TwSearchPuzzle_invertAlgorithm
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
